export const SAVE_CURRENT_USER_DATA = "SAVE_CURRENT_USER_DATA";
export const CLEAR_CURRENT_USER_DATA = "CLEAR_CURRENT_USER_DATA";
export const SAVE_CONNECTED_USER_DATA = "SAVE_CONNECTED_USER_DATA";
export const CLEAR_CONNECTED_USER_DATA = "CLEAR_CONNECTED_USER_DATA";
export const SAVE_EDITOR_DATA = "SAVE_EDITOR_DATA";
export const CLEAR_EDITOR_DATA = "CLEAR_EDITOR_DATA";
